### ISSUE TITLE
TypeError: Unspecified operation for type undefined for add

### ISSUE THREAD

**Issue by Leonardiae** [VeriBlock/vbk-ri-stratum-pool#6]
```
/root/vbk-ri-stratum-pool/packages/pool/node_modules/bignum/index.js:97
      throw new TypeError('Unspecified operation for type ' +
      ^

TypeError: Unspecified operation for type undefined for add
    at BigNum.<computed> [as add] (/root/vbk-ri-stratum-pool/packages/pool/node_modules/bignum/index.js:97:13)
    at Object.decode (/root/vbk-ri-stratum-pool/packages/pool/node_modules/base58-native/base58.js:49:23)
    at Object.exports.addressToScript (/root/vbk-ri-stratum-pool/packages/pool/lib/util.js:266:26)
    at /root/vbk-ri-stratum-pool/packages/pool/lib/pool.js:420:37
    at /root/vbk-ri-stratum-pool/packages/pool/lib/pool.js:422:15
    at /root/vbk-ri-stratum-pool/packages/pool/lib/daemon.js:134:13
    at parseJson (/root/vbk-ri-stratum-pool/packages/pool/lib/daemon.js:85:17)
    at IncomingMessage.<anonymous> (/root/vbk-ri-stratum-pool/packages/pool/lib/daemon.js:95:17)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1201:12)
```

**Comment by Leonardiae** [comment]
Added this issue just for reference so others know what the cause is. As described in the readme one need to set a legacy address in vbtc_config.json file. This error appears when a Bech32 address has been set.
